"""add owner

Revision ID: 3e06ec7a823b
Revises: e684f34b5334
Create Date: 2025-06-16 02:59:39.127906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e06ec7a823b'
down_revision: Union[str, None] = 'e684f34b5334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('owner', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'users', ['owner'], ['chat_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'owner')
    # ### end Alembic commands ###
