"""init

Revision ID: 8d00a371f707
Revises:
Create Date: 2025-06-16 03:04:42.360065

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8d00a371f707"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "servers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("remark", sa.String(length=64), nullable=False),
        sa.Column("enable", sa.Boolean(), nullable=True),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("access", sa.String(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_servers_id"), "servers", ["id"], unique=False)
    op.create_index(op.f("ix_servers_remark"), "servers", ["remark"], unique=False)
    op.create_table(
        "user_messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_messages_chat_id"), "user_messages", ["chat_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("chat_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(length=256), nullable=False),
        sa.Column("username", sa.String(length=128), nullable=True),
        sa.Column("join_at", sa.DateTime(), nullable=False),
        sa.Column("online_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("chat_id"),
    )
    op.create_index(op.f("ix_users_chat_id"), "users", ["chat_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("owner", sa.BigInteger(), nullable=True),
        sa.Column("server_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner"],
            ["users.chat_id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_id"],
            ["servers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_subscriptions_id"), "subscriptions", ["id"], unique=False)
    op.create_index(
        op.f("ix_subscriptions_key"), "subscriptions", ["key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_subscriptions_key"), table_name="subscriptions")
    op.drop_index(op.f("ix_subscriptions_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_users_chat_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_user_messages_chat_id"), table_name="user_messages")
    op.drop_table("user_messages")
    op.drop_index(op.f("ix_servers_remark"), table_name="servers")
    op.drop_index(op.f("ix_servers_id"), table_name="servers")
    op.drop_table("servers")
    # ### end Alembic commands ###
