"""add marzneshin tags

Revision ID: 533a9c913d3e
Revises: 8d00a371f707
Create Date: 2025-06-16 14:53:32.945637

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "533a9c913d3e"
down_revision: Union[str, None] = "8d00a371f707"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "marzneshin_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("key", sa.String(length=32), nullable=False),
        sa.Column("subscription_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"], ["subscriptions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_marzneshin_tags_id"), "marzneshin_tags", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_marzneshin_tags_key"), "marzneshin_tags", ["key"], unique=False
    )
    op.create_index(
        op.f("ix_marzneshin_tags_username"),
        "marzneshin_tags",
        ["username"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_marzneshin_tags_username"), table_name="marzneshin_tags")
    op.drop_index(op.f("ix_marzneshin_tags_key"), table_name="marzneshin_tags")
    op.drop_index(op.f("ix_marzneshin_tags_id"), table_name="marzneshin_tags")
    op.drop_table("marzneshin_tags")
    # ### end Alembic commands ###
